name: Build and Push ARM64 Docker Image

on:
  workflow_dispatch:
    inputs:
      image_name:
        description: 'Docker image name (e.g., your_dockerhub_username/alist-image)'
        required: true
        default: 'zhr520v/alist123'
      image_tag:
        description: 'Docker image version (e.g., v3.44.0)'
        required: true
        default: 'v3.44.0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检出仓库代码
      - name: Checkout code
        uses: actions/checkout@v2

      # 设置 Docker 镜像名称和标签
      - name: Set Docker image name and tag
        run: |
          IMAGE_NAME="${{ github.event.inputs.image_name }}"
          IMAGE_TAG="${{ github.event.inputs.image_tag }}"
          echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV

      # 下载 alist 二进制文件
      - name: Download alist binary for ARM64
        run: |
          mkdir -p alist
          curl -L https://github.com/zhr520v/Alist_123/releases/download/v3.44.0/alist-linux-musl-arm64.tar.gz -o alist.tar.gz
          tar -xzvf alist.tar.gz -C alist

      # 创建 Dockerfile
      - name: Create Dockerfile for ARM64
        run: |
          echo 'FROM alpine:latest' > Dockerfile
          echo 'RUN apk update && apk add --no-cache bash curl libc6-compat' >> Dockerfile
          echo 'WORKDIR /opt/alist' >> Dockerfile
          echo 'COPY alist/alist /opt/alist/alist' >> Dockerfile
          echo 'RUN chmod +x /opt/alist/alist' >> Dockerfile
          echo 'CMD ["/opt/alist/alist", "server"]' >> Dockerfile

      # 设置 Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 构建 ARM64 Docker 镜像
      - name: Build ARM64 Docker image
        run: |
          docker buildx build --platform linux/arm64 -t $IMAGE_NAME:$IMAGE_TAG .

      # 登录 Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 推送 Docker 镜像到 Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker buildx build --platform linux/arm64 -t $IMAGE_NAME:$IMAGE_TAG --push .
